import { Request, Response } from 'express';
import { Mark } from '../model/brand';
import { mark } from '../types/mark';
import fs from 'fs';
import path from 'path';

const markobject = new Mark();

export default class Markcontroller {
  addmark = async (req: Request, res: Response) => {
    try {
      const mark: mark = {
        name: req.body.name,
        image: req.body.filename // this is the filename generated by multer and stored in req.body.filename
      };

      const result = await markobject.create(mark);
      if (result) {
        res.json({ status: 'success', msg: 'Brand added successfully' });
        return;
      } else {
        res.json({
          status: 'fail',
          msg: 'There was an error adding the brand'
        });
        return;
      }
    } catch (err) {
      res.json({ status: 'fail', msg: 'There was an error adding the brand' });
      return;
    }
  };

  index = async (_req: Request, res: Response) => {
    try {
      const brands = await markobject.index();

      // Note: if there is no brands in db , we return empty array with success status
      if (brands.length > 0) {
        const data: mark[] = [];

        for (const value of brands) {
          const imagePath = path.join(
            __dirname,
            '../uploads/brands',
            value.image as string
          );

          try {
            const imageData = await fs.promises.readFile(imagePath);

            const imgData = {
              imageData: 'data:image/*;base64,' + imageData.toString('base64')
            };

            data.push({ ...value, ...imgData });
          } catch (err) {
            // IF there is error in getting any one image , we add '' value instead it
            data.push({ ...value, imageData: '' });
          }
        }

        res.json({ status: 'success', data: data });
        return;
      }
      res.status(404);
      res.json({ status: 'success', data: [] });
      return;
    } catch (err) {
      res.status(400);
      res.json({ status: 'fail', msg: 'There was an error fetching brands' });
      return;
    }
  };

  deletemark = async (req: Request, res: Response) => {
    try {
      if (!req.body.name) {
        res.json({ error: 'Name of brand should be provided (name)' });
        return;
      }

      const result = await markobject.deletemark(req.body.name);

      if (result) {
        res.json({ status: 'success', msg: 'Brand deleted successfully' });
        return;
      } else {
        res.status(404);
        res.json({
          status: 'Brand not found',
          msg: 'The brand you are trying to delete does not exist'
        });
        return;
      }
    } catch (err) {
      res.status(400);
      res.json({
        status: 'fail',
        msg: 'There was an error deleting the brand'
      });
      return;
    }
  };
}
