import { Request, Response } from 'express';
import { category } from '../types/category';
import { Category } from '../model/category';
import fs from 'fs';
import path from 'path';

const categoryobject = new Category();

export default class Categorycontroller {
  addcategory = async (req: Request, res: Response) => {
    try {
      const category: category = {
        name: req.body.name,
        image: req.body.filename // this is the filename generated by multer and stored in req.body.filename
      };

      const result: category | boolean = await categoryobject.create(category);
      if (result) {
        res.json({ status: 'success', msg: 'category added successfully' });
        return;
      } else {
        res.status(400);
        res.json({ status: 'error', msg: 'An error occurred while adding the category' });
        return;
      }
    } catch (err) {
      res.status(400);
      res.json({
        status: 'error',
        msg: 'An error occurred while adding the category'
      });
      return;
    }
  };

  index = async (_req: Request, res: Response) => {
    try {
      const categories: category[] = await categoryobject.index();

      if (categories.length > 0) {
        const data: category[] = [];

        for (const value of categories) {
          //const imagePath = path.join(
          //__dirname,
          //'../uploads/categories',
          //value.image as string
          //);

          const imagePath = path.join(
            process.cwd(),
            'uploads',
            'categories',
            value.image as string
          );

          try {
            const imageData = await fs.promises.readFile(imagePath);

            const imgData = { imageData: imageData.toString('base64') };

            data.push({ ...value, ...imgData });
          } catch (err) {
            // IF there is error in getting any one image , we add 'null' value instead it
            data.push({ ...value, imageData: '' });
          }
        }

        res.json({ status: 'success', categoriesCount: data.length, msg: 'Categories retrieved successfully', data: data });
        return;
      }
      res.status(404);
      res.json({ status: 'success', categoriesCount: 0, msg: 'No categories found', data: [] });
      return;

    } catch (e) {
      res.status(400);
      res.json({
        status: 'error',
        msg: 'An error occurred while retrieving categories'
      });
      return;
    }
  };

  deletecategory = async (req: Request, res: Response) => {
    try {
    
        // To Do : we should also delete the image of category from uploads folder .
        const result: boolean = await categoryobject.deletecategory(
          req.body.name
        );

        if (result) {
          res.json({ status: 'success', msg: 'category deleted successfully' });
          return;
        } else {
          res.status(404);
        res.json({
          status: 'fail',
          msg: 'category not found , it may be deleted or name isnt true'
        });
        return;
        }

    } catch (err) {
      res.status(400);
      res.json({
        status: 'error',
        msg: 'An error occurred while deleting the category'
      });
      return;
    }
  };
}
